name: Inspector de Sintaxis
on: [push, pull_request] # Se activa cada vez que alguien abre un PR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # El robot baja tu c√≥digo
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Revisar errores de sintaxis
      run: python -m py_compile clima.py # El robot intenta "leer" tu archivo
